24/06/22 (09:05:28) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3567, in _collect
    up_stat = psutil.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2221, in net_if_stats
    return _psplatform.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/_psosx.py", line 261, in net_if_stats
    names = net_io_counters().keys()
OSError: [Errno 12] Cannot allocate memory
24/06/22 (09:05:30) | WARNING: Exiting with errorcode (1). Runtime 10 days, 23:09:01 

24/06/22 (23:03:19) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3587, in _collect
    io_all = psutil.net_io_counters(pernic=True)[cls.nic]
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2114, in net_io_counters
    rawdict = _psplatform.net_io_counters()
OSError: [Errno 12] Cannot allocate memory
24/06/22 (23:03:21) | WARNING: Exiting with errorcode (1). Runtime 13:57:20 

19/07/22 (22:33:25) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3587, in _collect
    io_all = psutil.net_io_counters(pernic=True)[cls.nic]
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2114, in net_io_counters
    rawdict = _psplatform.net_io_counters()
OSError: [Errno 12] Cannot allocate memory
19/07/22 (22:33:27) | WARNING: Exiting with errorcode (1). Runtime 12 days, 7:34:56 

12/08/22 (17:44:35) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3587, in _collect
    io_all = psutil.net_io_counters(pernic=True)[cls.nic]
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2114, in net_io_counters
    rawdict = _psplatform.net_io_counters()
OSError: [Errno 12] Cannot allocate memory
12/08/22 (17:44:37) | WARNING: Exiting with errorcode (1). Runtime 15 days, 9:28:02 

19/08/22 (22:59:00) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3567, in _collect
    up_stat = psutil.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2221, in net_if_stats
    return _psplatform.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/_psosx.py", line 261, in net_if_stats
    names = net_io_counters().keys()
OSError: [Errno 12] Cannot allocate memory
19/08/22 (22:59:02) | WARNING: Exiting with errorcode (1). Runtime 4 days, 12:36:37 

27/09/22 (21:34:37) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3567, in _collect
    up_stat = psutil.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2221, in net_if_stats
    return _psplatform.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/_psosx.py", line 261, in net_if_stats
    names = net_io_counters().keys()
OSError: [Errno 12] Cannot allocate memory
27/09/22 (21:34:39) | WARNING: Exiting with errorcode (1). Runtime 36 days, 11:05:32 

28/10/22 (04:27:50) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3567, in _collect
    up_stat = psutil.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2221, in net_if_stats
    return _psplatform.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/_psosx.py", line 261, in net_if_stats
    names = net_io_counters().keys()
OSError: [Errno 12] Cannot allocate memory
28/10/22 (04:27:52) | WARNING: Exiting with errorcode (1). Runtime 6 days, 11:26:49 

04/11/22 (01:44:20) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3587, in _collect
    io_all = psutil.net_io_counters(pernic=True)[cls.nic]
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2114, in net_io_counters
    rawdict = _psplatform.net_io_counters()
OSError: [Errno 12] Cannot allocate memory
04/11/22 (01:44:21) | WARNING: Exiting with errorcode (1). Runtime 6 days, 9:50:01 

05/12/22 (04:45:21) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3567, in _collect
    up_stat = psutil.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2221, in net_if_stats
    return _psplatform.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/_psosx.py", line 261, in net_if_stats
    names = net_io_counters().keys()
OSError: [Errno 12] Cannot allocate memory
05/12/22 (04:45:22) | WARNING: Exiting with errorcode (1). Runtime 26 days, 18:54:43 

17/12/22 (06:36:39) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3567, in _collect
    up_stat = psutil.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2221, in net_if_stats
    return _psplatform.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/_psosx.py", line 261, in net_if_stats
    names = net_io_counters().keys()
OSError: [Errno 12] Cannot allocate memory
17/12/22 (06:36:41) | WARNING: Exiting with errorcode (1). Runtime 15 days, 20:25:01 

20/01/23 (10:31:15) | ERROR: Data collection thread failed with exception: [Errno 6] Device not configured
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3567, in _collect
    up_stat = psutil.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2221, in net_if_stats
    return _psplatform.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/_psosx.py", line 265, in net_if_stats
    mtu = cext_posix.net_if_mtu(name)
OSError: [Errno 6] Device not configured
20/01/23 (10:31:17) | WARNING: Exiting with errorcode (1). Runtime 4 days, 3:06:53 

09/02/23 (01:08:06) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3587, in _collect
    io_all = psutil.net_io_counters(pernic=True)[cls.nic]
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2114, in net_io_counters
    rawdict = _psplatform.net_io_counters()
OSError: [Errno 12] Cannot allocate memory
09/02/23 (01:08:08) | WARNING: Exiting with errorcode (1). Runtime 16 days, 10:22:40 

23/02/23 (00:16:25) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3567, in _collect
    up_stat = psutil.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2221, in net_if_stats
    return _psplatform.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/_psosx.py", line 261, in net_if_stats
    names = net_io_counters().keys()
OSError: [Errno 12] Cannot allocate memory
23/02/23 (00:16:27) | WARNING: Exiting with errorcode (1). Runtime 13 days, 15:28:48 

16/03/23 (05:06:09) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3587, in _collect
    io_all = psutil.net_io_counters(pernic=True)[cls.nic]
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2114, in net_io_counters
    rawdict = _psplatform.net_io_counters()
OSError: [Errno 12] Cannot allocate memory
16/03/23 (05:06:11) | WARNING: Exiting with errorcode (1). Runtime 8 days, 12:06:37 

11/07/23 (10:36:59) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3567, in _collect
    up_stat = psutil.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2221, in net_if_stats
    return _psplatform.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/_psosx.py", line 261, in net_if_stats
    names = net_io_counters().keys()
OSError: [Errno 12] Cannot allocate memory
11/07/23 (10:37:01) | WARNING: Exiting with errorcode (1). Runtime 36 days, 0:30:41 

31/08/23 (12:40:14) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 2958, in _runner
    collector._collect()
  File "/usr/local/lib/python3.10/site-packages/bpytop.py", line 3567, in _collect
    up_stat = psutil.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/__init__.py", line 2221, in net_if_stats
    return _psplatform.net_if_stats()
  File "/usr/local/lib/python3.10/site-packages/psutil/_psosx.py", line 261, in net_if_stats
    names = net_io_counters().keys()
OSError: [Errno 12] Cannot allocate memory
31/08/23 (12:40:15) | WARNING: Exiting with errorcode (1). Runtime 10 days, 5:08:10 

